import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/components-darkmode/theme-provider";
import localFont from "next/font/local";
// --- CONFIGURAÇÃO DE FONTES ---
const inter = localFont({
  src: "../public/fonts/Inter/static/Inter_18pt-Black.ttf",
  variable: "--font-inter",
});

const playfair = localFont({
  src: "../public/fonts/Playfair_Display/static/PlayfairDisplay-Bold.ttf",
  variable: "--font-playfair",
});

const jetbrainsMono = localFont({
  src: "../public/fonts/JetBrains_Mono/static/JetBrainsMono-ExtraBold.ttf",
  variable: "--font-jetbrainsMono",
});

const jura = localFont({
  src: "../public/fonts/Jura/static/Jura-Bold.ttf",
  variable: "--font-jura",
});

const leagueSpartan = localFont({
  src: "../public/fonts/League_Spartan/static/LeagueSpartan-Bold.ttf",
  variable: "--font-league-spartan",
});

const geistSans = localFont({
  src: "../public/fonts/Geist/static/Geist-Bold.ttf",
  variable: "--font-geist-sans",
});

const geistMono = localFont({
  src: "../public/fonts/Geist/static/Geist-ExtraBold.ttf",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${playfair.variable} ${jetbrainsMono.variable} ${jura.variable} ${leagueSpartan.variable} ${geistSans.variable} ${geistMono.variable} font-sans antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children} {/* Única chamada necessária aqui */}
        </ThemeProvider>
        {/* Removido o {children} que estava aqui embaixo */}
      </body>
    </html>
  );
}
